export const BUSINESS_CONFIG = {
  name: "AskAmritha",
  title: "AskAmritha | Premium AI Product Photography & Brand Visuals",
  description: "AskAmritha creates premium AI-powered product photos, fashion lookbooks, gourmet food styling, ad creatives, and professional personal branding profiles for entrepreneurs and small businesses.",
  whatsappNumber: "918591626408", // Update this with actual number (format: CCXXXXXXXXXX)
  whatsappMessage: "Hi Amritha, I'm interested in premium AI brand visuals and product photography. I'd love to know more!",
  email: "info@askamritha.com",
  phone: "+91 85916 26408",
  address: "India",
  domain: "www.askamritha.com",
  socials: {
    instagram: "https://www.instagram.com/askamritha/",
    facebook: "https://www.facebook.com/profile.php?id=61591658587008",
    pinterest: "https://pinterest.com/askamritha",
  },
  services: [
    {
      id: "ai-photography",
      title: "AI Product Photography",
      description: "Premium product visuals for skincare, jewellery, candles, perfumes, food, and lifestyle brands — created from simple product photos.",
      features: ["Custom background environments", "Perfect lighting & shadow matching", "4K resolution output", "Revisions available"],
      icon: "Camera",
    },
    {
      id: "ad-creatives",
      title: "AI Ad Creatives",
      description: "Scroll-stopping ad posters, launch creatives, sale graphics, and Instagram story visuals designed for small business promotions.",
      features: [
        "Offer and sale creatives",
        "Launch posters",
        "Instagram story designs",
        "Platform-ready sizes"
      ],
      icon: "Sparkles",
    },
    {
      id: "brand-visuals",
      title: "AI Model & Brand Shoots",
      description: "AI-powered model visuals for boutiques, jewellery brands, personal brands, founders, coaches, and creators.",
      features: [
        "Boutique lookbook visuals",
        "Jewellery model shots",
        "Founder profile visuals",
        "Monthly content packs"
      ],
      icon: "Layers",
    },
  ],
  pricing: [
    {
      id: "trial-pack",
      name: "Trial Pack",
      price: "₹999",
      period: "one-time",
      description: "Perfect to test the AI studio quality with your own products.",
      features: [
        "3 premium AI visuals",
        "High-resolution images",
        "48-hour delivery",
        "WhatsApp support",
        "1 revision included",
      ],
      cta: "Claim Trial Pack",
      popular: true,
    },
    {
      id: "essential",
      name: "Starter Pack",
      price: "₹2,499",
      period: "pack",
      description: "Ideal for launching new product lines or collections.",
      features: [
        "5 premium AI visuals",
        "2 visual styles",
        "High-resolution images",
        "3–4 days delivery",
        "1 revision included",
      ],
      cta: "Select Pack",
      popular: false,
    },
    {
      id: "growth",
      name: "Brand Growth Pack",
      price: "₹9,999",
      period: "Starting from",
      description: "Complete visual content for your monthly marketing campaign.",
      features: [
        "20 premium AI visuals",
        "5 ad creatives",
        "Multiple product styles",
        "Priority delivery",
        "2 revision rounds",
      ],
      cta: "Select Pack",
      popular: false,
    },
    {
      id: "bespoke",
      name: "Monthly Content Pack",
      price: "Custom",
      period: "monthly",
      description: "Tailored monthly volume packages for high-growth e-commerce catalogs.",
      features: [
        "20+ visuals monthly",
        "Product photos + ad creatives",
        "Festive and sale creatives",
        "Monthly content planning",
        "WhatsApp support",
      ],
      cta: "Discuss Monthly Pack",
      popular: false,
    },
  ],
  categories: [
    { name: "Cosmetics & Skincare", path: "/images/categories/skincare.png" },
    { name: "Fine Jewelry", path: "/images/categories/jewelry.png" },
    { name: "Fashion & Apparel", path: "/images/categories/fashion.png" },
    { name: "Food & Gourmet", path: "/images/categories/food.png" },
    { name: "Ad Creatives", path: "/images/categories/ads.png" },
    { name: "Personal Branding", path: "/images/categories/branding.png" },
    { name: "Tech Gadgets", path: "/images/categories/tech.png" },
    { name: "Luxury Accessories", path: "/images/categories/accessories.png" },
  ],
};
